name: Build

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle and build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootJar
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads

      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          cp build/libs/ga-*SNAPSHOT.jar .
          cd ..

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: downloads