name: Publish Artifacts

on:
  workflow_run:
    workflows: ["Java CI"]
    types: [requested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads

      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          cp build/libs/ga-*SNAPSHOT.jar .
          cd ..

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: downloads